const {chromium} = require('/Users/moinmoin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
(async()=>{
  const base=process.env.PAIR_TEST_URL, run=process.env.PAIR_TEST_RUN;
  assert(base && run, 'Use the isolated Python browser-test runner');
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  try {
    const page=await browser.newPage({viewport:{width:730,height:546}});
    const errors=[], external=[], dialogs=[];
    page.on('pageerror',e=>errors.push(e.message));
    page.on('request',r=>{if(!r.url().startsWith(base+'/')&&!r.url().startsWith('data:'))external.push(r.url());});
    page.on('dialog',d=>{dialogs.push(d.message());d.accept();});
    const state=async()=>(await page.request.get(base+'/api/state')).json();
    const saved=()=>page.waitForFunction(()=>document.querySelector('#save-status').textContent==='已在本機保存');
    const preview=()=>page.waitForFunction(()=>{const p=document.querySelector('#preview');return !p.hidden&&p.complete&&p.naturalWidth&&!document.querySelector('#preview-stage').hasAttribute('aria-busy');});
    const pick=n=>page.getByRole('button',{name:`選擇 下載 (${n}).jpeg`,exact:true}).click();
    await page.goto(base);
    await page.getByRole('button',{name:'編輯第 2 組',exact:true}).click();await preview();
    const previewCropToggle=page.getByRole('button',{name:'選擇裁切',exact:true});
    assert.equal(await previewCropToggle.isVisible(),true,'有配對時可選擇裁切預覽');
    assert.equal(await page.locator('#preview-crop-reset').isHidden(),true);
    await previewCropToggle.click();
    await page.waitForFunction(()=>{const b=document.querySelector('#preview-crop-box');return b&&!b.hidden&&document.querySelectorAll('.preview-crop-handle').length===8;});
    assert.equal(await page.locator('#crop-details .crop-help').count(),0,'移除裁切說明文字');
    assert.equal(await page.locator('.crop-note').count(),0,'移除裁切提示文字');
    assert.equal((await page.locator('#crop-details summary').innerText()),'自由裁切');
    assert.equal(await page.getByRole('button',{name:'取消裁切',exact:true}).isVisible(),true);
    await page.getByRole('button',{name:'取消裁切',exact:true}).click(); await preview();
    assert.equal(await page.getByRole('button',{name:'選擇裁切',exact:true}).isVisible(),true,'取消裁切會離開裁切模式');
    assert.equal(await page.locator('#preview-crop-box').isHidden(),true,'取消裁切會隱藏裁切框');
    assert.equal((await state()).groups[1].preview_crop,undefined,'第一次裁切取消後不留下裁切設定');
    await page.getByRole('button',{name:'選擇裁切',exact:true}).click();
    await page.waitForFunction(()=>{const b=document.querySelector('#preview-crop-box');return b&&!b.hidden&&document.querySelectorAll('.preview-crop-handle').length===8;});
    const previewTop=page.getByRole('slider',{name:'預覽裁切上邊（拖曳控制）',exact:true}), previewBottom=page.getByRole('slider',{name:'預覽裁切下邊（拖曳控制）',exact:true});
    await page.locator('#preview-frame').evaluate(el=>el.scrollIntoView({block:'center'}));
    const previewTopBox=await previewTop.boundingBox(); await page.mouse.move(previewTopBox.x+previewTopBox.width/2,previewTopBox.y+previewTopBox.height/2); await page.mouse.down(); await page.mouse.move(previewTopBox.x+previewTopBox.width/2,previewTopBox.y+previewTopBox.height/2+12); await page.mouse.up();
    const previewBottomBox=await previewBottom.boundingBox(); await page.mouse.move(previewBottomBox.x+previewBottomBox.width/2,previewBottomBox.y+previewBottomBox.height/2); await page.mouse.down(); await page.mouse.move(previewBottomBox.x+previewBottomBox.width/2,previewBottomBox.y+previewBottomBox.height/2-12); await page.mouse.up();
    await saved(); const previewCropped=await state(); assert(previewCropped.groups[1].preview_crop[1]>0 && previewCropped.groups[1].preview_crop[3]<10000,'預覽裁切拖曳確實改變上下邊並保存');
    await page.getByRole('button',{name:'完成裁切',exact:true}).click(); await preview();
    await page.locator('#crop-details summary').click();
    const topEdge=page.getByRole('slider',{name:'左圖裁切上邊（拖曳控制）',exact:true});
    const leftEdge=page.getByRole('slider',{name:'左圖裁切左邊（拖曳控制）',exact:true});
    const bottomEdge=page.getByRole('slider',{name:'左圖裁切下邊（拖曳控制）',exact:true});
    const topBox=await topEdge.boundingBox();
    await page.mouse.move(topBox.x+topBox.width/2,topBox.y+topBox.height/2);
    await page.mouse.down(); await page.mouse.move(topBox.x+topBox.width/2,topBox.y+topBox.height/2+18); await page.mouse.up();
    const bottomBox=await bottomEdge.boundingBox();
    await page.mouse.move(bottomBox.x+bottomBox.width/2,bottomBox.y+bottomBox.height/2);
    await page.mouse.down(); await page.mouse.move(bottomBox.x+bottomBox.width/2,bottomBox.y+bottomBox.height/2-18); await page.mouse.up();
    assert.equal(await page.locator('.crop-handle').count(),16,'兩張照片各有四邊與四角控制點');
    assert.equal(await page.locator('input[type="range"], .crop-range-row').count(),0,'不再顯示下方滑桿');
    assert((await page.locator('.crop-handle').first().boundingBox()).width<=20,'裁切圓點縮小');
    await saved();
    const dragged=await state(); assert(dragged.groups[1].left.box[3]-dragged.groups[1].left.box[1]>=20,'連續拖動上下邊仍保留最小裁切範圍');
    await topEdge.focus(); await topEdge.press('ArrowDown');
    await leftEdge.focus(); await leftEdge.press('ArrowRight');
    await bottomEdge.focus(); await bottomEdge.press('ArrowUp');
    await saved();
    const edited=await state(); assert(edited.groups[1].left.box[1]>0); assert(edited.groups[1].left.box[0]>edited.photos[2].white[0]); assert(edited.groups[1].left.box[3]<edited.photos[2].height);
    await page.getByRole('button',{name:'刪除第 1 組',exact:true}).click();await saved();
    assert.deepEqual((await state()).groups.map(g=>g.id),['second']);
    assert.equal(await page.locator('#editor-subtitle').textContent(),'正在調整第 1 組');
    assert.equal((await state()).photos.length,4);
    assert.equal(await page.locator('.photo').count(),2,'已配對照片從照片庫隱藏');
    assert.equal(await page.locator('.used-marker').count(),0,'不顯示已配對標籤');
    assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'刪除第 1 組');
    const exportResponse=page.waitForResponse(r=>r.url().endsWith('/api/export'));
    await page.locator('#export').click();const exported=await (await exportResponse).json();
    assert.equal(exported.count,3);
    assert.equal(exported.photo_count,2);
    assert.equal(exported.collage_count,1);
    await page.locator('#export').waitFor({state:'visible'});
    await page.waitForFunction(()=>!document.querySelector('#export').disabled);
    await page.reload();await page.getByRole('button',{name:'刪除第 1 組',exact:true}).click();await saved();
    assert.equal((await state()).groups.length,0);
    assert.equal((await state()).photos.length,4);
    assert.equal(await page.locator('#export').isDisabled(),false);
    const standaloneResponse=page.waitForResponse(r=>r.url().endsWith('/api/export'));
    await page.locator('#export').click();const standalone=await (await standaloneResponse).json();
    assert.equal(standalone.count,4);assert.equal(standalone.photo_count,4);assert.equal(standalone.collage_count,0);
    assert(fs.existsSync(path.join(exported.folder,'照片-001.jpg')));
    assert(fs.existsSync(path.join(exported.folder,'拼圖-001.jpg')));
    assert.equal(await page.evaluate(()=>document.activeElement.id),'export');
    assert.deepEqual(dialogs,[],'Deletion must not prompt');
    await pick(1);await pick(2);await page.locator('#add-pair').click();await saved();
    await pick(3);await pick(4);await page.locator('#add-pair').click();await saved();
    await page.getByRole('button',{name:'刪除第 2 組',exact:true}).focus();await page.keyboard.press('Enter');await saved();
    assert.equal(await page.locator('#preview').isHidden(),true,'Deleting active pair clears editor');
    await pick(3);await pick(4);await preview();
    await page.getByRole('button',{name:'刪除第 1 組',exact:true}).click();await saved();await preview();
    assert.equal(await page.locator('.photo[aria-pressed=true]').count(),2,'Other deletion keeps unsaved draft');
    assert.equal(await page.locator('#add-pair').isEnabled(),true);
    await page.locator('#add-pair').click();await saved();
    await pick(1);await pick(2);await page.locator('#add-pair').click();await saved();await preview();
    await page.locator('#crop-details summary').click();
    for(const [name,width,height] of [['desktop',1440,1000],['user-730',730,546],['mobile',390,844],['narrow-333',333,600]]) {
      await page.setViewportSize({width,height});await page.evaluate(()=>window.scrollTo(0,0));
      await page.screenshot({path:path.join(run,name+'.png'),fullPage:true});
      assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
      for(const button of await page.locator('.pair-delete').all()) {
        const rect=await button.boundingBox();assert(rect.width>=20 && rect.width<32 && rect.height>=20 && rect.height<32);
      }
    }
    await page.setViewportSize({width:730,height:546});
    assert.equal(await page.locator('#pair-mode').getAttribute('aria-pressed'),'true','預設為拼圖模式');
    await page.locator('#single-crop-mode').click();
    assert((await page.locator('#editor-title').textContent()).includes('單張裁切'),'切換後標題立即變為單張裁切');
    assert.equal(await page.locator('#swap').isHidden(),true,'單張裁切模式隱藏交換左右');
    await page.getByRole('button',{name:'選擇 下載 (3).jpeg',exact:true}).click();
    assert.equal(await page.locator('.photo[aria-pressed=true]').count(),1,'正在裁切的照片有明確選取樣式');
    await page.locator('#pair-mode').click();
    const availableCount=await page.locator('.photo').count();
    assert(availableCount>0,'切回拼圖模式後有可選照片');
    await page.locator('#single-crop-mode').click();
    const cropAvailable=await page.locator('.photo').count();
    assert(cropAvailable>=availableCount,'單張裁切模式可選照片數>=拼圖模式（不隱藏已配對）');
    await page.locator('#files-input').setInputFiles(path.join(run,'formats/格式測試.webp'));
    await page.getByText('已匯入 1 張',{exact:true}).waitFor();
    await page.locator('#folder-input').setInputFiles(path.join(run,'formats'));
    await page.getByText('已匯入 5 張，略過 1 張完全重複照片，另有 2 個檔案未匯入',{exact:true}).waitFor();
    assert.equal((await state()).photos.length,10);
    await page.locator('#import-issues summary').click();
    assert((await page.locator('#import-issues').textContent()).includes('動畫或多頁'));
    await page.getByRole('button',{name:'選擇 格式測試.webp',exact:true}).click();
    await page.getByRole('button',{name:'選擇 格式測試.avif',exact:true}).click();await preview();
    await page.locator('#add-pair').click();await saved();
    const response=page.waitForResponse(r=>r.url().endsWith('/api/export'));
    await page.locator('#export').click();const result=await (await response).json();
    assert.equal(result.count,7);assert.equal(result.photo_count,4);assert.equal(result.collage_count,3);assert(result.results.every(r=>r.bytes>0));
    assert(result.results.filter(r=>r.type==='collage').some(r=>r.sources.some(s=>s.name.endsWith('.webp'))));
    await page.route('**/api/ai-crop',async route=>{const id=JSON.parse(route.request().postData()).photo_ids[0],p=(await state()).photos.find(x=>x.id===id);await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({results:[{id,name:p.name,analysis:{},crop_box:[0,100,p.width,p.height],issues:[]}]})})});
    await page.locator('#ai-analyze').click();await page.waitForFunction(()=>document.querySelector('#ai-progress').textContent.startsWith('分析完成'));assert(await page.locator('#ai-results .ai-result').count()>0);
    await page.locator('#reset').click();await page.waitForFunction(()=>document.querySelector('#ai-results').hidden&&document.querySelector('#ai-progress').textContent==='');assert.equal((await state()).photos.length,0);assert.equal((await state()).groups.length,0);
    assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
    fs.writeFileSync(path.join(run,'result.json'),JSON.stringify({deletion:'no-confirm, active/inactive/draft/focus/empty/persistence passed',formats:'file WebP and folder JPEG/WebP/AVIF/BMP/TIFF/GIF passed, animated/corrupt rejected',exports:result,consoleErrors:errors,externalRequests:external},null,2));
    console.log('PASS: immediate X deletion, no confirmation, focus/persistence/other pairs/original photos/old exports preserved; common-format file/folder upload and export; 4 viewport sizes (333px included); mode switching regression; zero JS errors/external requests.');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
